###
GET http://localhost:3000/books
Content-Type: application/json

###
GET http://localhost:3000/books/978-1505689620
Content-Type: application/json

###
PUT http://localhost:3000/books/978-1505689620
Content-Type: application/json

{
    "title": "PHP7",
    "author": "Mr. Z",
    "price": 9.23
}

###
DELETE http://localhost:3000/books/978-1505689620
Content-Type: application/json

###
POST http://localhost:3000/books
Content-Type: application/json

{
    "isbn": "978-1505689620",
    "title": "PHP",
    "author": "Mr. X",
    "price": 9.23
}
